<template>
    <!-- Header -->
    <header class="flex w-full h-16 justify-between items-center px-6 bg-white/80 backdrop-blur-sm border-b border-gray-200">
        <div class="flex items-center gap-3">
            <div class="w-8 h-8 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center">
                <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z"></path>
                </svg>
            </div>
            <h1 class="text-xl font-semibold text-gray-900">Will It Rain?</h1>
            <span class="text-sm text-gray-500">NASA Space Apps Challenge</span>
        </div>

        <nav class="flex items-center gap-2">
            <NuxtLink href="/" class="inline-flex items-center gap-2 text-sm text-gray-700 hover:text-gray-900 px-3 py-2 rounded-lg border border-gray-200 bg-white hover:shadow-md transition-all">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0h6"></path></svg>
                Home
            </NuxtLink>
        </nav>
    </header>
    <div class="min-h-screen bg-gradient-to-br from-slate-50 to-white overflow-hidden">
        <main class="relative z-10 px-3 md:px-6 py-6 md:py-10">
            <div class="w-full max-w-none">
                <header class="mb-8 text-center">
                    <h1 class="text-4xl md:text-5xl font-bold text-gray-900 tracking-tight">Climate & Weather Statistics</h1>
                    <p class="mt-3 text-gray-700">Visual summaries generated by the backend and rendered from Markdown.</p>
                </header>

                <section class="bg-white/80 backdrop-blur-sm rounded-2xl border border-gray-200 shadow-xl p-4 md:p-8">
                    <div class="text-4xl font-bold text-gray-900 tracking-tight text-center mb-4">Overview</div>
                    <div class="md-content max-w-none" v-html="html"></div>
                </section>
            </div>
        </main>
    </div>
</template>

<script setup>
import { computed } from 'vue'
import MarkdownIt from 'markdown-it'

const md = new MarkdownIt({
    html: false,
    linkify: true,
    typographer: true,
    breaks: true,
})

// Note: Some filenames contain ':' which are URL-encoded as %3A
const config = useRuntimeConfig()
const backend = (config && config.public && config.public.backend) ? config.public.backend : 'http://127.0.0.1:8000'

const markdown = computed(() => `
---

## 🌧️ Precipitation (1h)

**Summary:** Short-term rainfall intensity and variability.

![Box](${backend}/static/precip_h_box.png) ![Histogram](${backend}/static/precip_h_hist.png) ![Line](${backend}/static/precip_h_line.png)

---

## ❄️ Snow Depth

**Summary:** Accumulated snow levels across the analysis period.

![Box](${backend}/static/snodb_box.png) ![Histogram](${backend}/static/snodb_hist.png) ![Line](${backend}/static/snodb_line.png)

---

## ☀️ Temperature (2m)

**Summary:** Near-surface air temperature trends and spread.

![Box](${backend}/static/t2m_box.png) ![Histogram](${backend}/static/t2m_hist.png) ![Line](${backend}/static/t2m_line.png)

---

## 💨 Wind Speed (10m)

**Summary:** Surface wind behavior and variability.

![Box](${backend}/static/wind_speed_box.png) ![Histogram](${backend}/static/wind_speed_hist.png) ![Line](${backend}/static/wind_speed_line.png)
`)

const html = computed(() => md.render(markdown.value))
</script>

<style>
/* Container typography and spacing */
.md-content {
    color: #1f2937; /* gray-800 */
}
/* Headings inside v-html need global/deep selectors */
.md-content h1,
.md-content h2,
.md-content h3 {
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: 800;
    color: #0f172a; /* slate-900 */
}
.md-content h1 { font-size: 2rem; line-height: 2.25rem; }
.md-content h2 { font-size: 1.5rem; line-height: 2rem; }
.md-content h3 { font-size: 1.25rem; line-height: 1.75rem; }
.md-content p {
    margin-top: 0.5rem;
    margin-bottom: 1.25rem;
}
.md-content strong {
    color: #0f172a; /* slate-900 */
}

/* Image presentation */
.md-content p:has(img + img) {
    display: grid;
    grid-template-columns: repeat(1, minmax(0, 1fr));
    gap: 1rem; /* space between plots */
    align-items: start;
}
@media (min-width: 768px) {
    .md-content p:has(img + img) {
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 1.25rem;
    }
}
@media (min-width: 1280px) {
    .md-content p:has(img + img) {
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 1.5rem;
    }
}
.md-content img {
    width: 100%;
    height: auto;
    border-radius: 0.75rem; /* rounded-xl */
    background: white;
    box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1);
    border: 1px solid rgba(148, 163, 184, 0.3); /* slate-300/30 */
}

/* Section dividers */
.md-content hr {
    margin: 2rem 0;
    border-color: rgba(203, 213, 225, 0.7); /* slate-300 */
}

/* Overview intro tweaks */
.md-content h1 {
    font-size: 2.25rem;
    line-height: 2.5rem;
    font-weight: 900;
    color: #0f172a;
    margin-bottom: 0.75rem;
}
</style>
